package io.jexxa.drivingadapter.rest;

public final class JexxaWebProperties
{
    /**
     * Defines the listening address used by the driving adapter
     */
    public static final String JEXXA_REST_HOST = "io.jexxa.rest.host";

    /**
     * Defines the http-port used by the driving adapter
     */
    public static final String JEXXA_REST_PORT = "io.jexxa.rest.port";

    /**
     * Defines the https-port used by the driving adapter
     */
    public static final String JEXXA_REST_HTTPS_PORT = "io.jexxa.rest.https.port";

    /**
     * Defines the location of the keystore that includes https-certifcates
     */
    public static final String JEXXA_REST_KEYSTORE = "io.jexxa.rest.keystore.location";

    /**
     * Defines the password of the keystore
     */
    public static final String JEXXA_REST_KEYSTORE_PASSWORD = "io.jexxa.rest.keystore.password";

    /**
     * Defines a file that includes the password of the keystore
     */
    public static final String JEXXA_REST_FILE_KEYSTORE_PASSWORD = "io.jexxa.rest.keystore.file.password";

    /**
     * Defines the path for the autogenerated OpenAPI
     */
    public static final String JEXXA_REST_OPEN_API_PATH = "io.jexxa.rest.openapi.path";
    /**
     * Defines the path for the autogenerated OpenAPI
     */
    public static final String JEXXA_REST_OPEN_API_SERVERS = "io.jexxa.rest.openapi.servers";

    /**
     * Defines the directory path to the static files provided via http(s) included in the jar
     */
    public static final String JEXXA_REST_STATIC_FILES_ROOT = "io.jexxa.rest.static.files.root";

    /**
     * Defines the directory path to the static files provided via http(s) outside the jar
     */
    public static final String JEXXA_REST_STATIC_FILES_EXTERNAL = "io.jexxa.rest.static.files.external";

    private JexxaWebProperties()
    {
        //private constructor
    }
}
