package io.jexxa.infrastructure.drivingadapter.rest;

public final class JexxaWebProperties
{
    /**
     * Defines the listening address used by the driving adapter
     */
    public static final String JEXXA_REST_HOST = "io.jexxa.rest.host";

    /**
     * Defines the http-port used by the driving adapter
     */
    public static final String JEXXA_REST_PORT = "io.jexxa.rest.port";

    /**
     * Defines the https-port used by the driving adapter
     */
    public static final String JEXXA_REST_HTTPS_PORT = "io.jexxa.rest.https_port";

    /**
     * Defines the location of the keystore that includes https-certifcates
     */
    public static final String JEXXA_REST_KEYSTORE = "io.jexxa.rest.keystore";

    /**
     * Defines the password of the keystore
     */
    public static final String JEXXA_REST_KEYSTORE_PASSWORD = "io.jexxa.rest.keystore_password";

    /**
     * Defines a file that includes the password of the keystore
     */
    public static final String JEXXA_REST_FILE_KEYSTORE_PASSWORD = "io.jexxa.rest.file.keystore_password";

    /**
     * Defines the path for the autogenerated OpenAPI
     */
    public static final String JEXXA_REST_OPEN_API_PATH = "io.jexxa.rest.open_api_path";

    /**
     * Defines the directory path to the static files provided via http(s) included into the jar
     */
    public static final String JEXXA_REST_STATIC_FILES_ROOT = "io.jexxa.rest.static_files_root";

    /**
     * Defines the directory path to the static files provided via http(s) outside of the jar
     */
    public static final String JEXXA_REST_STATIC_FILES_EXTERNAL = "io.jexxa.rest.static_files_external";

    private JexxaWebProperties()
    {
        //private constructor
    }
}
