= Jexxa - A hexagonal software architecture for your application
:source-highlighter: coderay
:toc:
:toclevels: 4
:icons: font
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:sectanchors:
:numbered:

//Hinweis: Die counter:local-table-number und counter:local-figure-number werden verwendet, damit im Fliesstext als Referenz die Nummer der Tabelle bzw. Abbildung angezeigt wird, also z.B. "wie in Abbildung 5 zu sehen ist"

== Vision
Jexxa is a lightweight framework to implement business applications based on a https://herbertograca.com/2017/11/16/explicit-architecture-01-ddd-hexagonal-onion-clean-cqrs-how-i-put-it-all-together/[ports and adapters] architecture. It shows how to easily connect technology stacks, called adapters, to interfaces of a technology agnostic application core which are called ports. For this purpose Jexxa offers:

* A lightweight core which manages the lifecycle of both ports and adapters.
* A well-defined interface to integrate arbitrary technology stacks.
* A fluent API that explicitly represents the binding between technology stacks and interfaces of the application core within the main method of an application.

Even though Jexxa is used within lightweight business applications and microservices it has a strong educational focus, especially on  following paradigms:

* _Dependency Inversion_: Get an idea how to strictly separate between technology stacks and domain logic on a code basis which is essential for durable business applications.

* _Simplicity_: Be aware of what technology stacks you really need to realize the customers' use cases. Usually they are much less than expected. Keep different technology stacks loosely coupled to facilitate their exchange. Finally, prefer a convention over configuration approach to standardize the integration of technology stacks and to reduce the complexity of their configuration.


* _Inversion of Control_(IoC): Find the required degree of IoC for your software projects. Control aspects that are technically required but not important for your business application should be hidden by a framework. The remaining required aspects should be explicitly represented.

Even if you use real powerful frameworks for good reason within your application I hope that you find Jexxa helpful in some way.

== Motivation
The main motivation to develop this framework comes from experiences with developing and maintaining durable software systems running up to 40 years. Here, the role of a sustainable software architecture becomes an important part to support and guide the developer team which is currently responsible for this application.

Existing frameworks such as the https://spring.io[Spring Framework] or the J2EE standard provide powerful features and greatly support development of complex business applications. On the other side, these frameworks can unintentionally be misused by developers from an architectural point of view. It is very difficult to maintain applications over several decades, especially when such frameworks find their way into the domain logic.

When developing applications with a high durability as used in production, financial or insurance sector, it is highly recommended using an architecture with a strict focus on separating technology stacks from the application core, such as ports and adapters. Within the application core, developers shall only use standard language features or libraries/SDKs shipped with a programming language. Available frameworks shall be used to attach the latest technology stacks to the application core.

Applications without well-defined boundaries between technology stacks and application core become difficult to maintain because changes on one side could (and in reality will) affect the other side. Typical symptoms are:

* Updating to a newer version of a technology stack is difficult or even impossible so that it is much safer to use the old one. Of course new developed applications use this old version as well because your team 'trusts' it, and you avoid maintaining a zoo of different versions.

* Adding or replacing a technology stack is difficult or even impossible, so a disruptive technology will cause your application core to become legacy as well. A common example are database technologies that have typically found their way into companies in the following chronological order: Hierarchical DBs -> relational DBs -> a zoo of NoSQL DBs. Because database technologies can become crucial for your business, your company employs senior-grade developers who have deep knowledge of both legacy and new technology stacks and synchronize your business data.

* Changes on the application core itself takes much longer time as in the beginning. In the end you need senior developers who have a deep understanding of the specific business domain, the used technology stacks and the convoluted structures of the entire application.

* In the long term, such structural issues could (and in reality will) affect your enterprise architecture, so neighboring systems need to be aware and take special actions for legacy systems.  


== General Building Blocks

Jexxa has a strong focus on Domain Driven Design and uses a lot of terminology from its strategic and tactical design. An application that is build on Jexxa provides components that belong either to the __application core__ or to the  __infrastructure__. The __application core__ includes the business logic whereas the __infrastructure__ provides required technology stacks.


<<JexxaComponents>> shows the separation of a Jexxa application into packages, the included components, and the relationship of the components among each other.


[plantuml, images/JexxaComponents, svg, align=center]
[reftext="Figure {counter:local-figure-number}"]
.This figure shows the separation of a typical Jexxa application into packages, the included components, and the relationship of the components among each other. Packages labeled with `\<<Jexxa>>` are provided by Jexxa. Packages labeled with `\<<Application>>` have to be realized by the application.
[[JexxaComponents]]
....
@startuml
skinparam PackagePadding 20

package JexxaCore <<Jexxa>> {
[Convention] <<Inversion of Control>>
[Core] <<Jexxa API>>
[Factory] <<Inversion of Control>>
}

package JexxaInfrastructure <<Jexxa>> {
[Generic Driving Adapters]  <<Driving Adapter>>
[Specific Driving Adapters] <<Driving Adapter>>
[Driven Adapter Strategies] <<Driven Adapter Strategy>>
}

package ApplicationCore <<Application>> {
[Inbound Ports] <<Port>>
[Outbound Ports] <<Port>>
}

package Infrastructure <<Application>> {
[Port Adapters] <<Driving Adapter>>
[Driven Adapters] <<Driven Adapter>>
}

[Specific Driving Adapters] o-right-> [Port Adapters]
[Generic Driving Adapters] o-right-> [Inbound Ports]

[Port Adapters] *-right-> [Inbound Ports]
[Inbound Ports] o-down-> [Outbound Ports]
[Outbound Ports] <|.. [Driven Adapters]
[Driven Adapters] o-left-[Driven Adapter Strategies]

[Factory] ..> Infrastructure : create
[Factory] ..> ApplicationCore : create
[Factory] ..> JexxaInfrastructure : create

[Generic Driving Adapters] -[hidden]- [Port Adapters]
[Generic Driving Adapters] -[hidden]- [Specific Driving Adapters]
[Specific Driving Adapters] -[hidden]- [Driven Adapter Strategies]
[Port Adapters] -[hidden]- [Driven Adapters]

[Core] -left-> [Factory]
[Core] -up-> [Convention]

@enduml
....

<<JexxaPackagetDescription>> describes the packages of an application based on Jexxa.

[cols="1,2"]
[reftext="Table {counter:local-table-number}"]
.Describes the packages of a typical application build with Jexxa.    
[[JexxaPackagetDescription]]
|===
a|Package
|Description

a|`ApplicationCore`
| This package includes your technology agnostic business application.

a|`Infrastructure`
a| This package includes the glue code to bind your technology agnostic business application to the package `JexxaInfrastructure`.

|`JexxaInfrastructure`
| This package includes the provided driving adapter of Jexxa as well as the driven adapter strategies which simplify the application specific driven adapter

a|`JexxaCore`
| This package includes the core of Jexxa and manages the lifecycle of both ports and adapters. The details are described in Section <<Inversion of Control (IoC)>>. The functionality of this package is used via a fluent API within the main method of your application.


|===

=== Package `ApplicationCore`
The components of package `ApplicationCore` are:

[cols="1,2,2"]
[reftext="Table {counter:local-table-number}"]
.Describes the components of package `ApplicationCore`.
[[ApplicationCoreComponentDescription]]
|===
a|Components
|General Description
|Support by Jexxa


a|`Inbound Ports`
| Inbound ports belong to the application core and provide use cases that can be started by a driving adapter. Depending on the design of your application core a port might be an interface, or a concrete implementation of a set of use cases.
a| * Jexxa provides implicit constructor injection for your inbound ports which is described in <<Dependency Injection (DI)>>.
* Jexxa also allows to instantiate and manage ports by yourself an just use provided driving adapters and driven adapter strategies.

a|Outbound Ports
a| Outbound ports belong to the application core but only as interface. These interfaces are implemented in package `Infrastructure` by a driving adapter which provides access to a specific technology stack such as a database driver.


a| Outbound ports are 'just' interfaces that must be defined by your application core. Jexxa provides support to implement these interfaces by so called __driven adapter strategies__.

|===


=== Package `Infrastructure`
The components of package `Infrastructure` are:


[cols="1,2,2"]
[reftext="Table {counter:local-table-number}"]
.Describes the components of package `Infrastructure`.
[[InfrastructureComponentDescription]]
|===
a|Components
|General Description
|Support by Jexxa



|Driven Adapters

|Driven adapters implement the outbound ports and can be injected into the inbound ports which in turn operates on these interfaces. Typically they map domain objects to a specific technology stack.
| Jexxa provides _driven adapter strategies_ to simplify development of driven adapters of an application.



| Port Adapters

| Port adapters allows for mapping between different representational styles of a specific port. For example this is required if a port should be exposed via a RESTful API. A port adapter belongs to the infrastructure of the application and is bind to a __specific driving adapter__.
| Providing receiving driving adapters that simplify the development of the port adapters.


|===



=== Package `JexxaInfrastructure`
The components of `JexxaInfrastructure` are:

[cols="1,2,2"]
[reftext="Table {counter:local-table-number}"]
.Describes the components of package `JexxaInfrastructure`.
[[JexxaComponentDescription]]
|===
a|Components
|General Description
|Realization in Jexxa


a| Generic/Specific Driving Adapters
a| Driving adapters belong to the infrastructure and receive commands from a specific client such as a UI, or a console and forwards them to connected ports.
a| Jexxa provides a convention and configuration approach for driving adapters.

A __generic__ driving adapter automatically exposes methods from connected inbound ports by using a convention. For example this can be used for an RPC mechanism.

A __specific__ driving adapter is used if a convention cannot be applied. Instead you have to implement a configuration within the infrastructure of your application in form of a __port adapter__. The port adapter is connected to the specific driving adapter and performs the mapping to expose a port. For example this is required for RESTfulHTTP.


|Driven Adapter Strategies

|Driven adapter strategies provide how to map objects from the application core to a specific technology stack. For example if you use a database for persisting your data, the strategy decides the ORM mapping of your objects.
| Jexxa provides some _driven adapter strategies_ to simplify development of driven adapters. If such a strategy is suitable for your application, the implementation of a driven adapter is just a facade which maps the interface of the outbound port to the methods of the strategy.

Available strategies in Jexxa are based on the standard javax interfaces (e.g. JMS or JDBC) and can be configured via `Properties`. This allows you to adjust the configuration to your development process. For example, you can easily switch your database technology between in memory or JDBC, or the used URL.

|===



=== Package `JexxaCore`

[cols="1,2,2"]
[reftext="Table {counter:local-table-number}"]
.Describes the components of package `JexxaCore`.
[[JexxaCoreComponentDescription]]
|===
a|Components
|General Description
|Realization in Jexxa

a| Core
a| This component includes class `JexxaMain` which is the entry point in the main-method of your application to use Jexxa.
a| `JexxaMain` provides a fluent API to explicitly show the binding of technology stacks to your inbound ports. In addition it provides a `BoundedContext` which allows to control your application in your environment.

a| Factory
a| Instantiates ports and adapters and manages their life cycle.
a| Jexxa supports implicit constructor injection which is described in <<Dependency Injection (DI)>>.

a| Convention
a| Provides classes to validate the compliance with conventions of ports and adapters.
a| Jexxa provides a fast fail approach regarding conventions. The conventions are described in <<Dependency Injection (DI)>>.

|===


== Inversion of Control (IoC)

=== Dependency Injection (DI)

Jexxa provides a simple DI mechanism to instantiate inbound ports of a business application and to inject required dependencies. Within Jexxa we only support _implicit constructor injection_ for following reason:

* Constructor injection ensures that the dependencies required for the object to function properly are available directly after creating the object.

* Fields assigned in the constructor can be final so that the object can be immutable or at least protect the corresponding fields.

* No special annotations or configuration files are needed so that the application core remains completely decoupled from Jexxa. 

Within Jexxa we use conventions described in <<JexxaConventions>> to explicitly limit the direction of dependencies as described in <<JexxaComponents>>. Compared to other frameworks these limitations could be considered puristic, but they provide good guard rails to clarify the single responsibility of your ports.

[cols="1,2,2"]
[reftext="Table {counter:local-table-number}"]
.Conventions used to realize implicit constructor injection.
[[JexxaConventions]]
|===
a|Components
|Conventions
|Reason


a| Driving Adapter
a| One of the following constructors must be available (checked in this order).

* Public Default constructor
* Public constructor with a single `Properties` attribute
* Public static factory method that gets no parameters and returns the type of the driving adapter
* Public static factory method with a single `Properties` parameter and returns the type of the requested driving adapter



a|
Using constructors or factory methods do not require any special annotations. Using `Properties` is a standard approach in Java to provide configuration information. Note: A driving adapter gets the same `Properties` object as `JexxaMain`.

a|Inbound Port
a|
1. A single public constructor.
2. Parameters of the constructor must be interfaces of required outbound ports.
3. A unique implementation of each interface exists in the search scope of Jexxa. This scope is defined by method `JexxaMain::addToInfrastructure`.

a|
1. Avoids ambiguity when choosing the constructor.  
2. Ports should be self-contained as much as possible. Therefore only outbound ports should be hand in. This ensures that the infrastructure is agnostic to domain logic and knows only the __interfaces__ required by the application core but not any other inner components.


a|Outbound Port
a| None
a| None


|Driven Adapter

a| 1. Only a single driven adapter implements a specific outbound port.
2. One of the following constructors must be available (checked in this order):
* Public default constructor
* Public constructor with a single `Properties` attribute
* Public static factory method that gets no parameters and returns the type of the Outbound Port (and not the type of the driven adapter)
* Public static factory method with a single `Properties` parameter and returns the type of the outbound port (and not the type of the driven adapter).

a| 1. Avoids ambiguity when choosing a Driven Adapter. At the moment you can only limit the search space of driven adapters on a package level.

2. Using constructors or factory methods do not require any special annotations.



| Port Adapter
a| 1. A single public constructor with a single attribute. The attribute is the concrete type of a specific port.
a| 1. A port adapter is tightly coupled to a specific port. Therefore, it gets its concrete type injected.

|===

=== Scope

Jexxa provides some simple mechanisms to define and control the scopes of ports and adapters which are described in this section.

==== Visibility of Ports and Adapters

By default, you have to tell Jexxa the location of your driven adapter and ports on a package level so that they can be created by Jexxa'S DI mechanism. This allows an application to specify used ports and adapters on a very fine-grained level.

==== Threading 
At the moment Jexxa ensure that only a single thread is active within the application core. This greatly simplifies the development of the application core itself. Furthermore, this approach should be sufficient due to following reason:

* Multi threading is typically essential within technology stacks and not within the application core itself.
* When you start developing your application you have typically only a limited number of users.
* When your application becomes a huge success and must scale to a lot of users you should scale it by running multiple instances of the application. Today's container solutions offer a much better scaling and managing approach.

==== Allocation scope of Dependencies
The allocation scope defines how many instances of components are created by Jexxa. This is described in <<JexxaScope>>.

[cols="1,2,2"]
[reftext="Table {counter:local-table-number}"]
.Allocation scope for the components in a Jexxa application.
[[JexxaScope]]
|===
a|Components
|Scope
|Reason


a| Driving Adapter
a| Is managed as singleton and reused when it is bind to different ports.

a|
Simplifies managing technical resources like network ports or IP addresses.

NOTE: In case you need a strict control how objects are exposed for example to different IP addresses, you have to use a specific driving adapter combined with port-adapter.

a|Inbound Port
a|
1. Inbound ports created by Jexxa are managed as singleton and reused if they are connected to different driving adapters.

2. Inbound ports created by the application can be bind to adapters. In this case the application has full control of the number of instances.


a|
1. The singleton scope supports designing stateless ports which is in general recommended.
2. This is only recommended if your application core cannot fulfill the conventions of Jexxa (see <<JexxaConventions>>).

a|Outbound Port
a| None
a| None


|Driven Adapter

a| Is managed as singleton and reused when it is injected into different ports.
a|
The singleton scope supports designing stateless outbound ports which is in general recommended.


| Port Adapter
a| Is always created new and not reused.
a| Allows fine grained control of how a driving adapter should expose the included port. For example you can define that specific ports are only available via a management IP address. 
|===

=== Transactions
Jexxa does not support any transaction when using multiple driven adapters in a single use case. Traditional enterprise frameworks for example spawn (often by default) a transaction between the used technology stacks, such as a database and a messaging system, to ensure that data is only written into the database when publishing it to a messaging bus is successful. This is a great feature if you really need it. Unfortunately, it is also often used to compensate programming errors or even a bad software design.

Instead, we recommend building your ports of the application core so that they provide an idempotent semantic.





