name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Java Support Matrix'

jobs:
  merge-me:
    name: Merge me!

    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@98f5cf6a9f7c0ebef4a253f9dffe6530e2c1bd7c
        with:
          GITHUB_TOKEN: ${{ secrets.MERGE_ME_SECRET }}
          PRESET: DEPENDABOT_MINOR
