name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Java Support Matrix'

jobs:
  merge-me:
    name: Merge me!

    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@5021dbb3e0c5aab35baea812fb197a0dfadc53a9
        with:
          GITHUB_TOKEN: ${{ secrets.MERGE_ME_SECRET }}
          PRESET: DEPENDABOT_MINOR
